from fastapi import FastAPI, Form, BackgroundTasks
from fastapi.responses import JSONResponse
from openai import OpenAI
from dotenv import load_dotenv
import requests
import os

# Load environment variables
load_dotenv(dotenv_path=".env")

# OpenAI client
client = OpenAI(
    api_key=os.getenv("OPENAI_API_KEY")
)

# Slack webhook URL
SLACK_WEBHOOK_URL = os.getenv("SLACK_WEBHOOK_URL")

# FastAPI app
app = FastAPI()

@app.get("/")
def home():
    return {"status": "AI ChatOps Assistant Running"}

# Background AI processing function
def process_incident(incident_text):

    try:

        prompt = f"""
        You are a Senior Cloud & DevOps Engineer.

        Analyze the following production incident.

        Provide:
        1. Severity Level
        2. Root Cause
        3. Impact
        4. Recommended Fix
        5. Prevention Strategy

        Incident:
        {incident_text}

        Format response professionally.
        """

        response = client.chat.completions.create(
            model="gpt-4.1-mini",
            messages=[
                {
                    "role": "system",
                    "content": "You are an expert cloud incident analyst."
                },
                {
                    "role": "user",
                    "content": prompt
                }
            ]
        )

        ai_analysis = response.choices[0].message.content

        slack_message = {
            "text": f"""
🚨 *AI INCIDENT ANALYSIS REPORT*

{ai_analysis}

🤖 Generated by AI ChatOps Assistant
"""
        }

        requests.post(
            SLACK_WEBHOOK_URL,
            json=slack_message,
            timeout=10
        )

    except Exception as e:

        error_message = {
            "text": f"❌ AI processing failed: {str(e)}"
        }

        requests.post(
            SLACK_WEBHOOK_URL,
            json=error_message,
            timeout=10
        )

# Slash command endpoint
@app.post("/slack/analyze")
def slack_analyze(
    background_tasks: BackgroundTasks,
    text: str = Form(...),
    user_name: str = Form(...)
):

    # Start background AI processing
    background_tasks.add_task(process_incident, text)

    # Immediate Slack response visible in channel
    return JSONResponse(
        content={
            "response_type": "in_channel",
            "text": f"""
🚨 *NEW INCIDENT RECEIVED*

👤 Triggered By: {user_name}

📝 *Incident Details:*
{text}

🤖 AI analysis in progress...
"""
        }
    )