from fastapi import FastAPI
from pydantic import BaseModel
from openai import OpenAI
from dotenv import load_dotenv
import requests
import os
from fastapi import Form
from fastapi.responses import JSONResponse

# Load environment variables
load_dotenv(dotenv_path=".env")

# OpenAI setup
client = OpenAI(
    api_key=os.getenv("OPENAI_API_KEY")
)

# Slack webhook
SLACK_WEBHOOK_URL = os.getenv("SLACK_WEBHOOK_URL")

# FastAPI app
app = FastAPI()

# Request model
class IncidentRequest(BaseModel):
    incident: str

# Endpoint
@app.post("/incident-alert")
def analyze_and_send(request: IncidentRequest):

    prompt = f"""
    You are a Senior Cloud & DevOps Engineer.

    Analyze the following production incident.

    Provide:
    1. Severity Level (Critical / High / Medium / Low)
    2. Root Cause
    3. Impact
    4. Recommended Fix
    5. Prevention Strategy

    Format response professionally for enterprise incident management.

    Incident:
    {request.incident}
    """

    # OpenAI response
    response = client.chat.completions.create(
        model="gpt-4.1-mini",
        messages=[
            {
                "role": "system",
                "content": "You are an expert cloud incident analyst."
            },
            {
                "role": "user",
                "content": prompt
            }
        ]
    )

    ai_analysis = response.choices[0].message.content

    # Send to Slack
    slack_message = {
                     "text": f"""
                     🚨 *AI INCIDENT ANALYSIS REPORT*

                     {ai_analysis}

                     🤖 Generated by AI ChatOps Assistant
                     """
                     }

    slack_response = requests.post(
                                   SLACK_WEBHOOK_URL,
                                    json=slack_message,
                                  timeout=5
                                   )

    print(slack_response.status_code)

    return {
             "status": "success",
             "message": "Incident analyzed and delivered to Slack",
             "analysis": ai_analysis
            }
# Endpoint for Slack slash command (no swagger  only slack )

@app.post("/slack/analyze")
def slack_analyze(text: str = Form(...)):

    try:

        prompt = f"""
        You are a Senior Cloud & DevOps Engineer.

        Analyze the following production incident.

        Provide:
        1. Severity Level
        2. Root Cause
        3. Impact
        4. Recommended Fix
        5. Prevention Strategy

        Incident:
        {text}

        Format response professionally.
        """

        response = client.chat.completions.create(
            model="gpt-4.1-mini",
            messages=[
                {
                    "role": "system",
                    "content": "You are an expert cloud incident analyst."
                },
                {
                    "role": "user",
                    "content": prompt
                }
            ]
        )

        ai_analysis = response.choices[0].message.content

        return JSONResponse(
            content={
                "response_type": "in_channel",
                "text": f"🚨 *AI Incident Analysis*\n\n{ai_analysis}"
            }
        )

    except Exception as e:
        return JSONResponse(
            content={
                "response_type": "ephemeral",
                "text": f"Error: {str(e)}"
            }
        )